In [1]:
from pathlib import Path
import ast

import pandas as pd


ROOT = Path.cwd().parent
CLEAN_FILE = ROOT / "data" / "clean" / "movies_clean.csv"

df = pd.read_csv(CLEAN_FILE)

df.head()

,movie_id,title,original_title,overview,tagline,release_date,runtime,original_language,genres,keywords,...,vote_count,status,adult,production_companies,production_countries,spoken_languages,belongs_to_collection,poster_path,backdrop_path,homepage
0,969681,Spider-Man: Brand New Day,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,A brand new day starts now.,2026-07-29,145.0,en,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","[{'id': 9678, 'name': 'mind control'}, {'id': ...",...,2949,Released,False,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'english_name': 'English', 'iso_639_1': 'en'...","{'id': 531241, 'name': 'Spider-Man (MCU) Colle...",/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,https://spidermanbrandnewday.movie
1,1423191,Resident Evil,Resident Evil,Medical courier Bryan unwittingly finds himsel...,A new era of evil.,2026-09-16,95.0,en,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...","[{'id': 9744, 'name': 'outbreak'}, {'id': 1034...",...,619,Released,False,"[{'id': 47, 'logo_path': '/i7Z9ot2o3N5Sa3HrF09...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'english_name': 'English', 'iso_639_1': 'en'...",NaN,/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg,/3icyRAqgakNcQn6aDVz9libFmBA.jpg,https://residentevil.movie
2,1368337,The Odyssey,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",Defy the gods.,2026-07-15,173.0,en,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'id': 3799, 'name': 'ship'}, {'id': 3265, 'n...",...,3976,Released,False,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...","[{'english_name': 'English', 'iso_639_1': 'en'...",NaN,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,/bulFtfy3oBQtCnAMSi7g6DSSds3.jpg,https://www.universalpictures.com/movies/the-o...
3,1101383,The End of Oak Street,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,Where goes the neighborhood.,2026-08-12,100.0,en,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","[{'id': 3822, 'name': 'teleportation'}, {'id':...",...,1704,Released,False,"[{'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'english_name': 'English', 'iso_639_1': 'en'...",NaN,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,https://www.endofoakstreet.com
4,1032863,The Love Hypothesis,The Love Hypothesis,"Olive Smith, a biology PhD candidate, and Dr. ...",Fake dating. Real chemistry.,2026-09-23,112.0,en,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 818, 'name': 'based on novel or book'}...",...,372,Released,False,"[{'id': 2531, 'logo_path': '/9MfCJ2G6Nrf9yyRj4...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'english_name': 'English', 'iso_639_1': 'en'...","{'id': 1783817, 'name': 'The Love Hypothesis C...",/vfZxVHextAGC70zrNhS8lsROqP1.jpg,/o7Oy9Gbx1CCyaweL8xUhtMW4Puq.jpg,https://www.amazon.com/dp/B0H4WZS7VX

In [2]:
df["release_date"] = pd.to_datetime(df["release_date"],errors="coerce")

df["genres"] = df["genres"].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])

df["keywords"] = df["keywords"].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])

In [3]:
df["release_year"] = df["release_date"].dt.year

In [5]:
df["release_month"] = df["release_date"].dt.month

In [8]:
df["release_decade"] = (df["release_year"] // 10) * 10

In [9]:
df[["release_date", "release_year", "release_month", "release_decade"]].head()

  release_date  release_year  release_month  release_decade
0   2026-07-29        2026.0            7.0          2020.0
1   2026-09-16        2026.0            9.0          2020.0
2   2026-07-15        2026.0            7.0          2020.0
3   2026-08-12        2026.0            8.0          2020.0
4   2026-09-23        2026.0            9.0          2020.0

In [10]:
df["genre_count"] = df["genres"].apply(len)

In [11]:
df[["title", "genres", "genre_count"]].head()

,title,genres,genre_count
0,Spider-Man: Brand New Day,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",3
1,Resident Evil,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",3
2,The Odyssey,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",3
3,The End of Oak Street,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",3
4,The Love Hypothesis,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",2

In [12]:
df["keyword_count"] = df["keywords"].apply(len)

In [13]:
df[["title", "keywords", "keyword_count"]].head()

,title,keywords,keyword_count
0,Spider-Man: Brand New Day,"[{'id': 9678, 'name': 'mind control'}, {'id': ...",19
1,Resident Evil,"[{'id': 9744, 'name': 'outbreak'}, {'id': 1034...",20
2,The Odyssey,"[{'id': 3799, 'name': 'ship'}, {'id': 3265, 'n...",18
3,The End of Oak Street,"[{'id': 3822, 'name': 'teleportation'}, {'id':...",17
4,The Love Hypothesis,"[{'id': 818, 'name': 'based on novel or book'}...",11

In [14]:
df["runtime_category"] = pd.cut(
    df["runtime"],
    bins=[0, 90, 120, 150, float("inf")],
    labels=["Short", "Medium", "Long", "Very Long"],
    include_lowest=True,
)

In [15]:
df[["title", "runtime", "runtime_category"]].head(10)

                       title  runtime runtime_category
0  Spider-Man: Brand New Day    145.0             Long
1              Resident Evil     95.0           Medium
2                The Odyssey    173.0        Very Long
3      The End of Oak Street    100.0           Medium
4        The Love Hypothesis    112.0           Medium
5            Coyote vs. Acme    103.0           Medium
6               After Impact     95.0           Medium
7                    The Fix    142.0             Long
8               The Mongoose     99.0           Medium
9                     Mutiny     96.0           Medium

In [16]:
df["runtime_category"].value_counts()

runtime_category
Medium       1666
Long          737
Short         358
Very Long     160
Name: count, dtype: int64

In [17]:
df[
    [
        "release_year",
        "release_month",
        "release_decade",
        "genre_count",
        "keyword_count",
        "runtime_category",
    ]
].head()

,release_year,release_month,release_decade,genre_count,keyword_count,runtime_category
0,2026.0,7.0,2020.0,3,19,Long
1,2026.0,9.0,2020.0,3,20,Medium
2,2026.0,7.0,2020.0,3,18,Very Long
3,2026.0,8.0,2020.0,3,17,Medium
4,2026.0,9.0,2020.0,2,11,Medium

In [18]:
df[
    [
        "release_year",
        "release_month",
        "release_decade",
        "genre_count",
        "keyword_count",
        "runtime_category",
    ]
].info()

<class 'pandas.DataFrame'>
RangeIndex: 2953 entries, 0 to 2952
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   release_year      2951 non-null   float64
 1   release_month     2951 non-null   float64
 2   release_decade    2951 non-null   float64
 3   genre_count       2953 non-null   int64
 4   keyword_count     2953 non-null   int64
 5   runtime_category  2921 non-null   category
dtypes: category(1), float64(3), int64(2)
memory usage: 118.6 KB